from enum import Enum


class ErrorCode(str, Enum):
    GENERIC = "GENERIC"
    ENV_MISSING = "ENV_MISSING"
    LOGIN_FAILED = "LOGIN_FAILED"
    FORBIDDEN = "FORBIDDEN"
    CONNECTION = "CONNECTION"
    TORRENT_NOT_FOUND = "TORRENT_NOT_FOUND"
    TORRENT_AMBIGUOUS = "TORRENT_AMBIGUOUS"
    FILE_MATCH_NOT_FOUND = "FILE_MATCH_NOT_FOUND"
    SNAPSHOT = "SNAPSHOT"
    RESTORE = "RESTORE"
    MEDIA_ID_AMBIGUOUS = "MEDIA_ID_AMBIGUOUS"
    MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND"
    SEASON_MISMATCH = "SEASON_MISMATCH"
    MOVE_FAILED = "MOVE_FAILED"
    RECHECK_FAILED = "RECHECK_FAILED"
    PRIME_CANDIDATE_MISSING = "PRIME_CANDIDATE_MISSING"
